3cn-ecn/nantralPlatform

- server/apps/home/templates/home/home.html
- server/apps/student/templates/student/list.html
- server/templates/base.html
événement --> évènement
. --> ·
> Modifications suite à la réu

- server/config/settings/base.py
- server/templates/base.html
Mise à jour de la barre de navigation
Réglage de la langue du site en français
Réglage du fuseau horaire sur Paris
> Update the navbar

- server/apps/roommates/templates/roommates/housing/detail.html
- server/apps/roommates/views.py
Prise en charge des champs à valeur None dans la detailView
> Detail view coloc

- server/apps/group/forms.py
- server/apps/group/models.py
- server/apps/group/templates/group/detail.html
- server/apps/group/views.py
- server/templates/base.html
- fix members add error
- fix member edit error in group update
- fix dissmissible alert
> various fixes

- server/templates/base.html
J'avais oublié de changer la version du style.css dans le template de base en fait
> Correct a bug with logo club

- server/apps/club/admin.py
Permet de modifier le type de clubs par lots
> Modifier type_bdx for club many at once

- server/apps/club/templates/club/list.html
Tentative de correction du bug d'affichage de la liste des clubs
> Correct bug

- server/apps/account/forms.py
- server/apps/account/migrations/0002_lower_all_accounts.py
- server/apps/account/tests.py
- server/apps/account/views.py
- server/apps/student/models.py
Resoud les soucis de lower/upper case dans les emails et uniformise tous les first name / last name en lower case.
Charge aux differeentes vues d'afficher les noms et prénom comme bon leur semble.
Close #243 
Close #144
> Issue email login

- .gitignore
- server/apps/account/forms.py
- server/apps/account/locale/en/LC_MESSAGES/django.po
- server/apps/account/templates/account/forgotten_pass.html
- server/apps/account/templates/account/login.html
- server/apps/account/templates/account/permanent_account_upgrade.html
- server/apps/account/templates/account/registration.html
- server/apps/account/templates/account/reset_password.html
- server/apps/account/templates/account/temporary_registration.html
- server/config/settings/base.py
First attempt at translation in english for the registration pages
> Translation registration

- server/apps/club/models.py
I delete this function but in fact it was useful
> Sort by bdx type

- server/apps/academic/views.py
Forgot to return context in get_context_data
> I am an idiot

- frontend/src/containers/clubMembers.tsx
- frontend/src/containers/clubMembers/interfaces.ts
- frontend/src/containers/clubMembers/studentCard.tsx
- frontend/src/containers/clubMembers/styles.ts
- frontend/src/containers/clubMembers/utils.ts
- frontend/webpack.config/webpack.common.js
- server/apps/club/api_urls.py
- server/apps/club/api_views.py
- server/apps/club/serializers.py
- server/apps/event/migrations/test_event_debug.py
- server/apps/group/templates/group/detail/detail.html
- server/apps/roommates/api_views.py
- server/apps/student/models.py
- server/apps/student/serializers.py
This is the first step to implementing a React based members editor.
> Add members sort

- .github/workflows/deploy.yml
- .gitignore
- frontend/package-lock.json
React compilation now takes place on GitHub.
> Fix react compilation

- server/install.sh
Add the creation of env file in the install script for UNIX systems.
> :sparkles:  Configure environment variables in install

- backend/requirements.txt
- frontend/package-lock.json
Correct also frontend dependencies
> Correct for python3.10

- frontend/src/containers/roommates/colocathlonCard/participateButton.tsx
Correction du bug lorsque l'on appuie sur le bouton pour participer dans une coloc : pb de token.
Vérifier que le bouton marche bien
le bouton marche
non
> add csrf token

- backend/Pipfile.lock
- backend/apps/home/views.py
Correct a bug on feature/bug submission: the link to the user contained a `"` after the `https://`, which broke the link.
> Correct bug with Github Issues

- Makefile
- docs/docs/dev/get-started/install-party.md
- docs/docs/dev/get-started/setup-project.md
Correct the install process for Windows
> correct install

- .github/workflows/deploy-server.yml
Correct the workflow to update the server when there is no changes to the frontend
> correct deploy server

- backend/apps/home/urls.py
- backend/apps/home/views.py
- backend/static/assetlinks.json
Add the assetlinks file for the Google Play Application
> add assetlinks

- backend/apps/home/views.py
> remove leading slashes

- Makefile
- docs/docs/dev/get-started/config-tools.md
- docs/docs/dev/get-started/install-party.md
- docs/docs/dev/get-started/setup-project.md
- docs/docusaurus.config.js
- docs/package-lock.json
Correct the installation process for Windows in the `Makefile` file.
> Docs and install

- backend/static/assetlinks.json
Update the assetlinks file with the SSH key for the Android Application.
> Update the assetlinks file for Android app

- backend/apps/notification/forms.py
- backend/static/manifest.webmanifest
- frontend/src/containers/app/appInstallBanner.tsx
* Replace the default navigator installation by play store installation on Android (allow some improvments like hiding the default "settings" button)
* correct the notification setttings page
* correct the label for "Clubs & Assos" shortcut in manifest
> correct bugs

- .github/pull_request_template.md
*What did you done in this PR?*
Fix a minor typo.
* ...
* ...
> chore: fix typo

- frontend/src/components/Button/JoinButton.tsx
- frontend/src/components/NavBarSide/NavBarSide.tsx
- frontend/src/theme.ts
> Changement nul

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/Event/Event.scss
- frontend/src/pages/Event/Event.tsx
- add mui library, 'lab'
- create event page and switch between 'list' and 'calendar'
Creating and initing the event page
Click on Event section in the NavBarSide
Then switch between list and calendar
The tab switchs
> create and init event page

- frontend/src/pages/Event/Calendar.tsx
- frontend/src/pages/Event/Event.scss
- frontend/src/pages/Event/Event.tsx
- add a file to dev the calendar
- modify Event to include the calendar
- try to get event from BDD in Event.tsx
Init file to developp the calendar for the events
Go to the calendar interface in event
A draft (a beginning draft) of the calendar
> added Calendar.tsx

- frontend/src/components/NavBarSide/NavBarSide.tsx
- frontend/src/components/NavBarTop/NavBarTop.tsx
- frontend/src/pages/Event/Event.scss
- frontend/src/translations/en-GB.json
- frontend/src/translations/fr-FR.json
J'ai implémenté un bouton pour changer la langue du texte, ainsi que des traductions pour les menus
Ouvrir le menu utilisateur
Cliquer sur le menu de choix de langue
Choisir la langue voulue
La langue a changée
> Implémentation changement langages + traduction

- frontend/src/App.tsx
- frontend/src/components/NavBarTop/NavBarTop.tsx
- frontend/src/pages/Event/Event.scss
- frontend/src/pages/LegalNotice/Legal.tsx
- frontend/src/translations/en-GB.json
- frontend/src/translations/fr-FR.json
Creation of the Legal Notice page and traduction of the text in it.
> React app legal

- .gitignore
- .vscode/settings.json
- frontend/src/components/Button/JoinButton.tsx
- frontend/src/components/ClubAvatar/ClubAvatar.scss
- frontend/src/components/ClubAvatar/ClubAvatar.tsx
- frontend/src/components/EventCard/EventCard.tsx
- frontend/src/pages/Home/Home.scss
- frontend/src/pages/Home/Home.tsx
- frontend/src/pages/Props/Club.tsx
- frontend/src/pages/Props/Event.tsx
- frontend/src/translations/en-GB.json
- frontend/src/translations/fr-FR.json
- frontend/src/utils/formatText.ts
Added my clubs in home page
Updated eventProps
Added translation in joinButton
* Make sure you are member of clubs.
* Add events with a ticketing link
* You will see your clubs at the bottom of the home page
* The join buttons will redirect to ticketing links
> React app home layout

- frontend/src/pages/Event/Event.tsx
Deleted some code smells in event
> delete code smells

- frontend/src/components/NavBarTop/NavBarTop.tsx
- frontend/src/pages/Home/Home.tsx
Adapt the Top and Side Navbars, as well as the Home page to the mobile interfaces.
Press F12
Go into "mobile simulation" mode
Change the size of the window
Be amazed
> React app mobile

- .github/workflows/check-checks.yml
> add check-checks

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Calendar/Calendar.tsx
Add export ics.
- Create some events when you want.
- Go to the calendar in the event page.
- Go to a week with some of yours events.
- Click on the export button.
You get your events in an ics file and you can add it into your calendar.
> added export events functionnality for the calendar

- frontend/src/App.tsx
- frontend/src/components/NavBarSide/NavBarSide.tsx
- frontend/src/components/NavBarTop/NavBarTop.tsx
- frontend/src/translations/fr-FR.json
Implémentation d'un stockage local, permettant de conserver les choix de l'utilisateur concernant la langue ou le thème de l'application
> React app local storage

- .github/workflows/test-frontend.yml
- frontend/src/components/Calendar/Calendar.tsx
> try to setup test coverage

- .github/workflows/test-frontend.yml
- frontend/.gitignore
- frontend/jest.config.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/sonar-project.properties
- frontend/src/components/Calendar/Calendar.tsx
- frontend/src/tests/ChooseDisplay.test.tsx
- frontend/src/tests/Day.test.tsx
- frontend/src/tests/EventBlock.test.tsx
> React app test coverage

- frontend/package-lock.json
- frontend/src/components/Section/EventSection/EventSection.tsx
- frontend/src/pages/Event/Event.tsx
The eventsList has now some events to display
Need to improve because accordion still used
Go to events page and see the list of events
See something like the screenshot
> update eventlist to look good

- backend/apps/event/models.py
fixed issue with backend api and admin interface
> [URGENT] Fix backend issues

- backend/apps/group/serializers.py
- frontend/src/containers/group/MembershipsGroup.tsx
- frontend/src/containers/group/components/ListMembershipsTable.tsx
- frontend/src/containers/group/components/ModalArchiveMember.tsx
- frontend/src/containers/utils/form.tsx
Correct few things on memberships:
* Show an "Archive" icon instead of a "Delete" icon in memberships admin panel
* Add an "Archive" modal which asks to archive a member (update the `end_date` to the day before the actual day)
* Prevent updating dates to `null` for an existing membership with dates
> Correct memberships

- frontend/src/components/Calendar/Calendar.scss
- frontend/src/components/Calendar/Calendar.tsx
- frontend/src/components/Calendar/ChooseDisplay/ChooseDisplay.tsx
- frontend/src/components/Calendar/ChooseWeek/ChooseWeek.tsx
- frontend/src/components/Calendar/Day/Day.tsx
- frontend/src/components/Calendar/Day/EventBlock/EventBlock.tsx
- frontend/src/components/Calendar/DayInfos/DayInfos.tsx
- frontend/src/components/Calendar/utils.tsx
- frontend/src/tests/Calendar/ChooseDisplay.test.tsx
- frontend/src/tests/Calendar/Day.test.tsx
- frontend/src/tests/Calendar/EventBlock.test.tsx
Fix some bugs and improve calendar
Go to event page.
> React app improve calendar global display fix bug

- deployment/containers/nginx/global_nginx.conf
- deployment/containers/nginx/server_nginx.conf
> correct error on nginx conf

- backend/apps/home/templates/errors/403.html
- backend/apps/home/templates/errors/404.html
- backend/apps/home/templates/errors/500.html
- deployment/containers/nginx/custom_413.html
- deployment/containers/nginx/server_nginx.conf
Correct last bugs for 413 errors page
> last bugs on 413 custom page

- .github/workflows/quality.yml
- backend/apps/group/tests.py
> add final task

- frontend/src/pages/EventDetails/components/EventParticipantsModal.tsx
Fixed #1078 
Go to an event page, click on a participant.
No 404 error should be displayed
Make sure to update the code once the student page is created so that the page is not reloaded.
> fixed 404 error

- backend/apps/account/forms.py
- backend/apps/account/templates/account/confirm-email.html
- backend/apps/account/urls.py
- backend/apps/account/utils.py
- backend/apps/account/views.py
> add resend email option

- frontend/src/pages/Event/EventCalendar/CalendarGridView/CalendarGridView.tsx
> increase pagesize for month calendar

- deployment/docker-compose.prod.yml
> fix: webmail not available after reboot

- frontend/src/pages/Event/EventGrid/EventGridView.page.tsx
- frontend/src/shared/hooks/useDesktopMode.ts
Remove autofocus to fix bug (since it was not very useful)
> fix: remove autofocus on events page

- backend/apps/event/api_views.py
Fix shotgun filter on event page
> 1104 bug le filtre shotgun sur la page devent ne fonctionne pas

- frontend/src/pages/EventDetails/components/BackgroundImageOverlay.tsx
- frontend/src/pages/EventDetails/components/TopImage.tsx
- frontend/src/pages/Home/__snapshots__/Home.page.test.tsx.snap
- frontend/src/shared/components/BackgroundImage/BackgroundImage.tsx
Fix animations of images. The grey effet take the same times as the sliding animation now
> fix: animations of images

- backend/apps/account/migrations/0010_idregistration_expires_at_user_email_next_and_more.py
- backend/apps/account/models.py
> Hot fix migration failing

- .github/workflows/deploy-staging.yml
Finally fix this pipeline (I hope)
> fix: staging pipeline

- README.md
- docs/docs/dev/learning/git-tutorials/daily-workflow.mdx
- docs/docs/dev/learning/git-tutorials/github-desktop-tutorial.mdx
Update doc and ReadMe to ensure that people will not clone the repository to their personnal accounts
> Readme doc update

- frontend/src/modules/account/view/shared/RegisterFormFields.tsx
> fix: correct key for master

- backend/apps/account/admin.py
- backend/apps/account/serializers.py
User saved before assigning username so that id is not None :sweat_smile:
> Hot fix/unique username

- backend/config/settings/production.py
> fix email connection

- backend/apps/group/api_views.py
- backend/apps/group/models.py
- backend/apps/group/serializers.py
- backend/apps/group/tests.py
- frontend/src/modules/group/api/updateSubscription.api.ts
- frontend/src/modules/group/infra/group.adapter.ts
- frontend/src/modules/group/infra/group.dto.ts
- frontend/src/modules/group/types/group.types.ts
- frontend/src/pages/GroupDetails/components/Buttons/SubscribeButton.tsx
- frontend/src/pages/GroupDetails/components/GroupInfo.tsx
- frontend/src/pages/GroupDetails/hooks/useGroupDetails.ts
- frontend/src/shared/i18n/en-GB.json
- frontend/src/shared/i18n/fr-FR.json
Bring back the subscription button :relieved:
> Subscribe button

- backend/apps/family/algorithm/old_version.py
- backend/apps/family/models.py
- backend/apps/family/serializers.py
- backend/apps/family/templates/family/family/edit.html
Demande du BDE : autoriser des familles de 8 parains
> 8 parains par famille
