- .github/pull_request_template.md
- README.md
- backend/templates/base.html
* Add a link to the documentation website in the user menu
* Explain how to install a package for the frontend in the readme
* Add a default template for pull requests on github
* Open the user menu on the main website
* Click the "Documentation" link
* It should open the documentation website
> Add doc link on website

- backend/apps/tools/templates/tools/signature_gen.html
* Remove the `<td>` tag on the option
* Generate a signature
* Check that there is no `<td>` tag arround the option
Avant :
Après :
> correct signature bug

- backend/apps/student/templates/student/student_cards.html
- frontend/src/containers/group/groupMembers/studentCardPicture.tsx
* Add a circle behind the avataaar for more consistency
* Remove the extra `}` at the end of slugs when calling the image
> correct bug with avataaars

- backend/apps/roommates/admin_views.py
- backend/apps/roommates/templates/roommates/admin/home.html
Sur la page admin du colocathlon il y avait parrainage au lieu de colocathlon et aussi une ligne était en double
* ...
* ...
> fix duplication colocathlon

- deployment/containers/web/Dockerfile
- deployment/containers/web_staging/Dockerfile
- deployment/docker-compose.override.yml
- deployment/docker-compose.prod.yml
- deployment/docker-compose.yml
Change the `context` for building containers from the `root` directory to the `backend` directory.
This should avoid docker trying to read files (for examples ones from `mail` services) that it doesn't need to read.
It runs on my machine 🙃
> move context from root to backend

- backend/apps/notification/tasks.py
Fix errors that would prevent celery tasks from running.
Associated log
```
[2023-01-17 22:36:44,488: ERROR/ForkPoolWorker-1] Task apps.notification.tasks.clean_notifications[8ad8ea55-7938-4b36-8f9b-06eef4e9f0a9] raised unexpected: TypeError("'day' is an invalid keyword argument for __new__()")
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/var/app/apps/notification/tasks.py", line 40, in clean_notifications
timeperiod = datetime.timedelta(day=60)
TypeError: 'day' is an invalid keyword argument for __new__()
```
> fix: celery errors

- frontend/src/components/Calendar/Calendar.scss
- frontend/src/components/Calendar/Calendar.tsx
- Special time (0:00:00) and too long events work
- Possibility to switch between weeks
- Create some events *when you want*
- Try to do some of them with common time area, with very long duration, and in different weeks
- Go to the calendar in the event page
- The events appear at a good place on the calendar
> switch week and fix set event

- frontend/src/components/Accordion/SimpleAccordion.scss
- frontend/src/components/Accordion/SimpleAccordion.tsx
- frontend/src/components/Checkbox/CheckboxesTags/CheckboxesTags.tsx
- frontend/src/components/DatePicker/BasicDatePicker.tsx
- frontend/src/components/FilterBar/FilterBar.tsx
- frontend/src/pages/Event/Event.tsx
- Get all filters from Filterbar into Event page
- Create filter function that filters events according to the filter (for shotgun, je participe, favoris and date)
- Fix some width problems in the filterbar
- Changing the order of the filters in the filterbar
Go on the Event Page and click on the 'filtrer' button : 
- the 3 checkboxes are at the top of the two accordion filters
- on mobile phone and on computer : the width of the checkboxes and accordions adapt to the width of the drawer
- In the console, you can see an array that contains the events to display. When you choose a value in a filter (except for organisateur), and click on 'valider', the array is filtered and only contains the events that match the filter.
> React app event filter function

- backend/apps/group/api_views.py
- backend/apps/group/serializers.py
- backend/apps/group/templates/group/detail.html
- backend/apps/group/tests.py
- backend/apps/student/templates/student/profile.html
- backend/apps/utils/searchAPIMixin.py
- backend/config/settings/base.py
- frontend/package-lock.json
- frontend/src/containers/group/MembershipsGroup.tsx
- frontend/src/containers/group/MembershipsStudent.tsx
- frontend/src/containers/group/components/ModalEditMember.tsx
- frontend/src/containers/group/interfaces.ts
Add a paginator for groups and memberships apis. It limits the number of items downloaded by 50 by default, and give an url to download the next (or previous) 50 ones.
Add also a `simple` query paramters for group, allowing to only fetch the minimum possible data instead of every details of each item.
Remove the constraint to give a type for group api.
Remove the constraint to give a group or a student for membership api.
In the front end, the `res.data` object returned from axios is now an object of type `{ count: number; previous: string; next: string; results: T[] }`, where `results` is the list of requested objects, instead of just the list of objects. 
Note that it only affects `list` actions (i.e. the `GET /api/<app>/<table>/` endpoint), and not all the other actions (create, …
> Update Group APIs

- frontend/src/components/EventCard/EventCard.scss
- frontend/src/components/EventCard/EventCard.tsx
The content of an EventCard is now resized according to the size of the card. This allows cards to be scaled proportionally and dynamically, so they can be easily adapted to mobile devices or when the window is resized.
> Thumbnail - Resizable content

- frontend/src/components/NavBarTop/NavBarTop.tsx
Le 1er lien ("accueil" pour la page d'accueil) n'est un lien que si ce n'est pas le dernier lien, contrairement à avant.
Les breadcrumbs disparaissent en version mobile, car sinon seuls les "/" apparaissent, moyen stylé.
Aller sur la page d'accueil : "accueil" apparait, mais n'est pas cliquable.
Aller sur une autre page : "accueil" cliquable apparait, ainsi que le nom (non-cliquable) de la page courante.
Cliquer sur "accueil" : on revient sur la page d'accueil.
(sur la page "accueil")
(sur la page "évènement")
(sur mobile)
> React app crumbs

- frontend/src/components/Calendar/ChooseWeek/ChangeWeek/ChangeWeek.tsx
- frontend/src/components/Calendar/ChooseWeek/ChooseWeek.tsx
- frontend/src/components/Calendar/ChooseWeek/DateBox/DateBox.tsx
- frontend/src/components/Calendar/Day/Day.tsx
Fix resize of ChooseWeek component
Go to calendar in the event page and test multiple size of screen
It adapts itself
> fix auto resize in chooseWeek component

- deployment/docker-compose.prod.yml
If Nginx starts before the prod Django container is up and listening for requests, Nginx will fail all requests redirected to the (not yet available) upstream.
This fix checks that nantral-platform.fr is accessible every 30s and restarts the Nginx container if needed.
Most importantly, this will allow us to reboot our VPS without having to manually restart Nginx (this caused the website to be down on the 11th of May 2023
> fix: nginx upstream resolution fail

- backend/apps/family/forms.py
- backend/apps/family/views.py
Fixed a typo is_2Aplus and removed the option to add non subscribed members during the family creation to prevent exploits.
- Create a new family as a EI2
- No option to add non subscribed members appears
> Bug parrainage

- Makefile
Change the equivalent of the bash export in makefile for windows to ensure a correct setup of the PIPENV_VENV_IN_PROJECT variable
Run make install after cloning the repo in powershell or in cmd on windows.
The command will work, whereas before it quitted with an error saying "PIPENV_VENV_IN_PROJECT  1 is not defined
Old behavior
Correct execution of the script after the change
> Change export in makefile for powershell

- deployment/docker-compose.override.yml
- deployment/docker-compose.prod.yml
- deployment/scripts/certbot-renew.sh
Prevent certbot to create a new certificate when a domain is added to or removed from the list.
TO-DO: `git reset --hard`  on the server to remove custom edits (but only when we can generate again certificates)
> fix: remove force-renew

- backend/apps/account/admin.py
- backend/apps/account/forms.py
- backend/apps/account/locale/en/LC_MESSAGES/django.po
- backend/apps/account/models.py
- backend/apps/account/utils.py
- backend/apps/account/views.py
Solve issue #1139 
When upgrading to a definitive account with a ECN email address, we must transform the email into lowercase before saving it.
> fix: clean email to lowercase when upgrading from temporary account

- backend/apps/group/templates/abstract_group/included/navbar_edit.html
Masque l'onglet ***Membres*** dans la page d'édition des colocs, parce que yen a marre d'avoir des issues pour ça
> feat: hide members tab on roommates edit page

- deployment/stack/postgres.yml
Fix the timezone issue.
I'm not 100% sure why it's happening. My guess is that we spawned the database in UTC. Then, in https://github.com/3cn-ecn/nantralPlatform/pull/1281/files#diff-2b55e4c5b746598b1dd89b62c657486786aaf3faca0d6c95c7225f619d47e164 we (me) modified the compose file to make the database timezone aware. It seems like it messed up the timestamps.
We can keep the database timezone unaware for now.
Event 496 was scheduled between 21h and 22h CEST, directly from the UI.
```
nantral_staging=# select start_date, title, id from event_event where id = 496;
start_date       |       title       | id  
------------------------+-------------------+-----
2025-04-02 21:00:00+02 | Test des familles | 496
(1 row)
```
```
nantral_staging=# SELECT start_date, timezone('UTC', start_date), …
```
> fix(1291): timezone issue

- frontend/src/pages/Login/Login.page.tsx
Ajout d'un bouton pour renvoyer l'email de vérification dans le message d'erreur de la page de connexion.
Le but est de permettre aux utilisateurs qui n'ont pas reçu le mail de connexion et qui ont fermé la page de pouvoir se connecter à nouveau.
> feat: Add a button in login page to resend an email if it is not valid
